site_name: Ansible Tutorial
nav:
  - Home: index.md
  - Bootcamp:
    - Setting up the Environment: "setup.md"
    - Ad Hoc Server Maangement with Ansible: "ad-hoc.md"
    - Writing Playbook for Base System Configurations: "playbooks.md"
    - Configuring app server environment with Roles: "roles.md"
    - Making roles reusable with vars and templates: "templates_and_variables.md"
    - Setting up Load Balancer with Ansible Galaxy: "galaxy.md"
    - Controlling execution flow with conditionals, iterators and tags: "control_structures.md"
    - Auto discovery and multi environments: "magicvars_envs.md"
    - Encrypting sensitive data with Ansible Vault: "ansible-vault.md"
    - Setting up Zero Downtime Deployment: "update.md"
  - Additional Topics :
    - Dynamic Inventory: "dynamic_inventory.md"
    - Ansible on Windows: "ansible-windows.md"
    - Ansible Pull: "ansible-pull.md"
    - Ansible Tower: "ansible-pull.md"
    - Registered Variable: "registered_variables.md"
    - Custom Module: "custom_modules.md"
  - Troubleshooting:
    - Troubleshooting Techniques: "troubleshooting.md"
docs_dir: chapters
theme: readthedocs
site_url: http://ansible-tutorial.schoolofdevops.com/
site_author: Gourav Shah
site_description: Ansible Tutorial by School of Devops
google_analytics: ['', 'ansible-tutorial.schoolofdevops.com']
repo_url: https://github.com/schoolofdevops/zero-to-docker
edit_uri: edit/master/manuscript
copyright: Copyright @ 2017-2020 Gourav Shah, School of Devops. Some rights reserved. License CC BY-NC-SA
extra:
  social:
    - type: 'github'
      link: 'https://github.com/schoolofdevops'
    - type: 'twitter'
      link: 'https://twitter.com/gouravhah'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/gouravshah'
